/* automatically generated by rust-bindgen 0.72.1 from CEF 145.0.26 */

use crate::raw::{
    cef_base_ref_counted_t, cef_browser_t, cef_errorcode_t, cef_frame_t, cef_string_t,
    cef_transition_type_t,
};
type _cef_browser_t = cef_browser_t;
type _cef_frame_t = cef_frame_t;

#[repr(C)]
pub struct _cef_load_handler_t {
    pub base: cef_base_ref_counted_t,
    pub on_loading_state_change: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut _cef_load_handler_t,
            browser: *mut _cef_browser_t,
            isLoading: ::core::ffi::c_int,
            canGoBack: ::core::ffi::c_int,
            canGoForward: ::core::ffi::c_int,
        ),
    >,
    pub on_load_start: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut _cef_load_handler_t,
            browser: *mut _cef_browser_t,
            frame: *mut _cef_frame_t,
            transition_type: cef_transition_type_t,
        ),
    >,
    pub on_load_end: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut _cef_load_handler_t,
            browser: *mut _cef_browser_t,
            frame: *mut _cef_frame_t,
            httpStatusCode: ::core::ffi::c_int,
        ),
    >,
    pub on_load_error: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *mut _cef_load_handler_t,
            browser: *mut _cef_browser_t,
            frame: *mut _cef_frame_t,
            errorCode: cef_errorcode_t,
            errorText: *const cef_string_t,
            failedUrl: *const cef_string_t,
        ),
    >,
}
pub type cef_load_handler_t = _cef_load_handler_t;
