/* automatically generated by rust-bindgen 0.72.1 from CEF 145.0.26 */

use crate::raw::cef_string_t;
type _cef_string_utf16_t = cef_string_t;

#[repr(C)]
pub struct _cef_request_context_settings_t {
    pub size: usize,
    pub cache_path: cef_string_t,
    pub persist_session_cookies: ::core::ffi::c_int,
    pub accept_language_list: cef_string_t,
    pub cookieable_schemes_list: cef_string_t,
    pub cookieable_schemes_exclude_defaults: ::core::ffi::c_int,
}
pub type cef_request_context_settings_t = _cef_request_context_settings_t;
