#!/usr/bin/env bash
set -euo pipefail

PINNED_CEF_VERSION="145.0.26+g6ed7554+chromium-145.0.7632.110"
PINNED_CEF_API_VERSION="14500"
OUTPUT_DIR="crates/switchboard-cef-sys/src"

usage() {
  echo "usage: $0 [--check] <cef_distribution_root>" >&2
  exit 1
}

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
  shift
fi
[[ $# -eq 1 ]] || usage

CEF_ROOT="$1"
README_PATH="$CEF_ROOT/README.txt"
INCLUDE_DIR="$CEF_ROOT/include"
LOAD_HEADER="$INCLUDE_DIR/capi/cef_load_handler_capi.h"
TYPES_HEADER="$INCLUDE_DIR/internal/cef_types.h"

command -v bindgen >/dev/null 2>&1 || {
  echo "bindgen CLI not found; install bindgen-cli before regenerating" >&2
  exit 1
}
command -v rustfmt >/dev/null 2>&1 || {
  echo "rustfmt not found" >&2
  exit 1
}
[[ -f "$README_PATH" && -f "$LOAD_HEADER" && -f "$TYPES_HEADER" ]] || {
  echo "CEF distribution is missing README.txt or required headers: $CEF_ROOT" >&2
  exit 1
}
grep -Fq "CEF Version:      $PINNED_CEF_VERSION" "$README_PATH" || {
  echo "CEF distribution does not match pinned version $PINNED_CEF_VERSION" >&2
  exit 1
}

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/switchboard-cef-bindings.XXXXXX")"
trap 'rm -rf "$TMP_ROOT"' EXIT

LOAD_RAW="$TMP_ROOT/load.raw.rs"
LOAD_OUT="$TMP_ROOT/generated_load_handler_145.rs"
CONTEXT_RAW="$TMP_ROOT/context.raw.rs"
CONTEXT_OUT="$TMP_ROOT/generated_request_context_145.rs"

if ! bindgen "$LOAD_HEADER" \
  --output "$LOAD_RAW" \
  --allowlist-type '.*cef_load_handler_t' \
  --no-recursive-allowlist \
  --blocklist-type 'cef_base_ref_counted_t' \
  --blocklist-type '.*cef_browser_t' \
  --blocklist-type '.*cef_frame_t' \
  --blocklist-type 'cef_string_t' \
  --blocklist-type 'cef_errorcode_t' \
  --blocklist-type 'cef_transition_type_t' \
  --raw-line 'use crate::raw::{cef_base_ref_counted_t, cef_browser_t, cef_errorcode_t, cef_frame_t, cef_string_t, cef_transition_type_t};' \
  --raw-line 'type _cef_browser_t = cef_browser_t;' \
  --raw-line 'type _cef_frame_t = cef_frame_t;' \
  --no-layout-tests \
  --no-doc-comments \
  --use-core \
  --rust-target 1.82 \
  -- \
  "-I$CEF_ROOT" \
  "-DCEF_API_VERSION=$PINNED_CEF_API_VERSION" \
  2>"$TMP_ROOT/load.stderr"; then
  cat "$TMP_ROOT/load.stderr" >&2
  exit 1
fi

if ! bindgen "$TYPES_HEADER" \
  --output "$CONTEXT_RAW" \
  --allowlist-type '.*cef_request_context_settings_t' \
  --no-recursive-allowlist \
  --blocklist-type '.*cef_string_utf16_t' \
  --blocklist-type 'cef_string_t' \
  --raw-line 'use crate::raw::cef_string_t;' \
  --raw-line 'type _cef_string_utf16_t = cef_string_t;' \
  --no-layout-tests \
  --no-doc-comments \
  --use-core \
  --rust-target 1.82 \
  -- \
  "-I$CEF_ROOT" \
  "-DCEF_API_VERSION=$PINNED_CEF_API_VERSION" \
  2>"$TMP_ROOT/context.stderr"; then
  cat "$TMP_ROOT/context.stderr" >&2
  exit 1
fi

{
  echo "/* automatically generated by rust-bindgen 0.72.1 from CEF 145.0.26 */"
  tail -n +2 "$LOAD_RAW"
} > "$LOAD_OUT"
{
  echo "/* automatically generated by rust-bindgen 0.72.1 from CEF 145.0.26 */"
  tail -n +2 "$CONTEXT_RAW"
} > "$CONTEXT_OUT"
rustfmt "$LOAD_OUT" "$CONTEXT_OUT"

if [[ $CHECK_ONLY -eq 1 ]]; then
  cmp "$LOAD_OUT" "$OUTPUT_DIR/generated_load_handler_145.rs"
  cmp "$CONTEXT_OUT" "$OUTPUT_DIR/generated_request_context_145.rs"
  echo "CEF 145 bindings snapshot is current."
else
  cp "$LOAD_OUT" "$OUTPUT_DIR/generated_load_handler_145.rs"
  cp "$CONTEXT_OUT" "$OUTPUT_DIR/generated_request_context_145.rs"
  echo "Updated checked-in CEF 145 bindings snapshot."
fi
